version: '3.8'

services:
  # API service - FastAPI application
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: satu-peta-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL={DATABASE_URL}
      - DEBUG=0
      - HOST=0.0.0.0
      - PORT=5000
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - MINIO_ENDPOINT_URL=minio:9000
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SECURE=False
      - MINIO_BUCKET_NAME=satu-peta
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
    networks:
      - credential-manager-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload